### ISSUE TITLE
Fix in MP file

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus-old#12]
There are now some errors in the MP file that needs to be fixed

- [ ] We need to have dates instead of years for period in parliament
- [x] Some MP names are missing.
- [x] it seems like there are different party names and abbrivation mixed up.
- [ ] Not all MP have their job title.

**Comment by ninpnin** [comment]
This might come in handy: https://sv.wikipedia.org/wiki/Lista_%C3%B6ver_politiska_partier_i_Sverige#Historiska_rikspartier

**Comment by ninpnin** [comment]
And this: https://sv.wikipedia.org/wiki/Sveriges_regering#Sveriges_minist%C3%A4rer_och_regeringar

**Comment by MansMeg** [comment]
Indeed!

**Comment by ninpnin** [comment]
MP names fixed 👍

**Comment by ninpnin** [comment]
The dates of the MP terms seem to be elusive, while election days and government terms are relatively easy to find. Should we look more into this or keep no 1 on hold for now?

**Comment by fredrik1984** [comment]
Regarding MP terms I think we can keep it on hold for now. It is not the most important metadata for us at the moment.

**Comment by ninpnin** [comment]
Following the progress in #29
