### ISSUE TITLE
Remove marginal notes from speeches

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus-old#14]
We need to look for marginal notes etc. and remove those. 

I'm not sure how to do that in the best way? Some might be manually removed. But I also guess we could use BERT to identify? Or some simpler method. this should come into the curation database.

Although, they might be useful to add additional metadata on speeches (what debate they are within?)

**Comment by ninpnin** [comment]
Marginal notes have two distinct characteristics which can be used in their detection:

1) They are distinct in content; a lot of dates, days and certain descriptive words (protocol X on matter Y on Tuesday 6th June 2020)
2) They are repeated multiple times in the document

Currently, I'm using a heuristic which detects short paragraphs with a high proportion of non-alphabetic characters. It picks up maybe 50% of the margin note blocks, and I haven't come across a false positive yet. In the current implementation, they are not used for finding the metadata.

**Comment by MansMeg** [comment]
So how are we going to do this? I guess adding it to be removed in the curation database?

**Comment by ninpnin** [comment]
Yes this how it is currently done

**Comment by MansMeg** [comment]
Great!

**Comment by ninpnin** [comment]
Closing for now

**Comment by MansMeg** [comment]
Has it been removed?

**Comment by ninpnin** [comment]
Most of them are.

This is done by detecting recurring paragraphs and paragraphs with relatively high proportion of non-alphabetic characters.

If all you have is the paragraphs, you'd need some pretty high level NLP to reach >=95%. And I suggest we don't go there yet.

**Comment by MansMeg** [comment]
Indeed! So all these instances that are removed are now in the database? So we could essentially enumerate all these editions if we want?
