### ISSUE TITLE
Clean up the repo for additional users

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus-old#18]
Before we include additional users with the repo, we should clean it up:
- [x] Sort in code in a subdirectory. In the long run into python and R libraries?
- [x] Focus should be users on the main page. If I want to use the corpus, what should I do?
- [x] If I want to add a correction/contribute (or a ton of them). How do I do?

**Comment by ninpnin** [comment]
See wiki
