### ISSUE TITLE
Add the digital images to a sister repo using git lfs

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus-old#20]
Add a map to images names and images stored in a sister repo

**Comment by ninpnin** [comment]
https://github.com/welfare-state-analytics/riksdagen-corpus-images

**Comment by MansMeg** [comment]
Cool. Can you get the images up there with git lfs?

**Comment by ninpnin** [comment]
I'll calculate a file size estimate before starting the download

**Comment by ninpnin** [comment]
Github might send some warning emails if we go over 5GB. They say they don't have hard caps but I don't know how the go about crazy bandwidth use in practice.

**Comment by ninpnin** [comment]
I'm in the process of adding <pb> page begin elements with links to betalab images. I don't think we want to add images on GitHub.

**Comment by MansMeg** [comment]
Agree!
