### ISSUE TITLE
Extract subsets of the corpora in various formats

### ISSUE THREAD

**Issue by ninpnin** [welfare-state-analytics/riksdagen-corpus-old#26]
An end user might want to extract subsets from the corpora. I suggest we provide the ability to restrict the scope by
- A year range
- Protocol ID(s)
- Certain MPs
  - Hand-pick MPs
  - Choose all MPs with certain characteristics (eg. party) from the database

It would be natural to provide different output formats for this functionality. Minimally, I'd suggest we provide parla-clarin, and a plaintext format.

**Comment by MansMeg** [comment]
I think this is good. Although maybe not for the beta 0.1?

**Comment by ninpnin** [comment]
Fair enough. Good to plan before implementing in any case.
