### ISSUE TITLE
Suggest a new curation process

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus-old#30]
Väinö will write down a new curation process for discussion and then implementation

**Comment by ninpnin** [comment]
Is this the same as #28 ?

**Comment by ninpnin** [comment]
The current state of the manual curation is documented in the wiki https://github.com/welfare-state-analytics/riksdagen-corpus/wiki/Submit-corrections

**Comment by MansMeg** [comment]
Great! I’ll look at it and try it asap.

**Comment by ninpnin** [comment]
Documented in the Wiki.
