### ISSUE TITLE
Setup a test suite and git actions for CI

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus-old#31]
When we update the corpus or change it, we should do some quality check automatically using git actions. The things I can come up with are:
- [x] The test and training set we have annotation should not be changed (that's a gold standard)
- [x] Test the MEP that there are no missing values
- [x] Validate the parla clarin example file against the parla-clarin schema
- [x] Validate one-protocol-long parla clarin corpus generated by our code against the parla-clarin schema
- [x] Check that there is no reduction in the absolute number of missing values? I.e so we do not happen to remove party or similar?
- [x] Checks that MP only have speeches during the period where they are actually active in parliament

**Comment by ninpnin** [comment]
Current state of CI:
1. Validate the parla clarin example file against the parla-clarin schema
2. Validate one-protocol-long parla clarin corpus generated by our code against the parla-clarin schema

**Comment by MansMeg** [comment]
Cool. Maybe easier if you fix the initial CI @ninpnin ?

**Comment by ninpnin** [comment]
Considering test case 2 by Måns, the proportions of missing entries are:

name 0.0
party 0.008336491095111784
district 0.03306176582038651
chamber 0.0
start 0.0
end 0.0
occupation 0.7755778704054566
gender 0.18416066691928762
id 0.0

Where should we set the bar?

**Comment by MansMeg** [comment]
Good point! Maybe only check that there are no missing values for the variables we know should be full. I.e. id and name?

Also, maybe check that there is no reduction in the absolute number of missing values? I.e so we do not happen to remove party or similar?

I think that should be sufficient for now. Then we can add tests later on.

**Comment by MansMeg** [comment]
Add testsuite that chacks that MEP only have speeches during the period where they are actually active in parliament.

**Comment by ninpnin** [comment]
I added parla clarin validation. Now for a pull request, all changed and added XML files are tested against the Parla-Clarin schema. See #52

**Comment by ninpnin** [comment]
I added a test that checks that the name, party, district, chamber, and id columns have over 95% of the entries present.

**Comment by MansMeg** [comment]
Great! I think ID and Name need to be 100%?

**Comment by ninpnin** [comment]
Fixed.

**Comment by MansMeg** [comment]
Great! I updated the comment to capture the issues we listed here so we know when the issue is done. One of your tests, I didn't really understand.

**Comment by ninpnin** [comment]
Added a test that checks the validity of one protocol per type (ak, fk, ek, digital originals)

**Comment by ninpnin** [comment]
The last test case would necessitate running it on all protocols, right? That sounds a bit unattainable. EDIT: maybe pick 5-10 files and check that the tagged MPs in those files were active at the time.

**Comment by MansMeg** [comment]
Why not run on all protocols? How much time would such a test take?

One solution would be to run those test only in a test branch and the main branch if it takes a long time? I mean it doesn't matter to us if it runs for an hour?

**Comment by ninpnin** [comment]
Good news: I actually overestimated the time this test would take, it's actually only a minute or so. Bad news: there are some 30 protocols with wrongly tagged MPs.

**Comment by MansMeg** [comment]
Thats good news! Then we have found a bug!

**Comment by ninpnin** [comment]
Fair enough!

All of the planned CI tests are now implemented, by the way.
