### ISSUE TITLE
Add/generate speech IDs for now

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus-old#33]
It needs to be globaly unique

**Comment by ninpnin** [comment]
Does it need to be somewhat static ? If so, I'm thinking **prot-YYYY--NO-SPEAKER_ID_SPEECH_INDEX**

**Comment by MansMeg** [comment]
Hi! Yes it is good to have a static and globally unique id. I expect us to use this extensively.

**Comment by ninpnin** [comment]
Done. https://github.com/welfare-state-analytics/riksdagen-corpus/commit/37948675c976a1e260128ad6cfcb6878916d9c4f
