### ISSUE TITLE
Cleanup the repo

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus-old#67]
It is now quite difficult to navigate in the repository due to:

- [x] There is a lot of python files in the root. Can these be moved, either into a scripts folder och to a python library
- [x] There are now one folder called db and one called data. We should keep all the actual content in one place.
- [x] Additional data used for segmentation and processing of the data, but that is not intended to be used by end users should probably have its own folder
- [x] Do we need to keep the segmentation instances now with the new design structure? I think this should now be handled by git, right?
- [x] All documentation stuff such as img and similar folders should probably be moved to a docs folder.

What do you say @ninpnin ?

**Comment by ninpnin** [comment]
Fair points. What's the priority of this?

**Comment by MansMeg** [comment]
I think it is good to get it in place quite early since people might start to build based on our paths.

**Comment by ninpnin** [comment]
Done.
