### ISSUE TITLE
Incorrect README?

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus-old#69]
This is now where the protocols are: - Annual protocol files under ```data/protocol/```
They seem to be here: ```data/protocol/new-parlaclarin```

I guess we want to make this more explicit. Im not sure about the other contents in the protocols folder?

**Comment by ninpnin** [comment]
I actually think the protocols could have a dedicated ```corpus``` folder. Gotta check what scripts I need to update.

**Comment by MansMeg** [comment]
Yes. That sounds like a good idea. I found it to be slightly confusing to find the right folder. So I think we should have one folder that contain all data of interest (maybe data) and move out examples etc.

Also, maybe already in the README point to documentation on what each file contain. Im still not sure. Is each file a protocol now? I looked at file 11000 and then it seemed like the date was incorrect? It said 2018-01-01 in the teiHeader?

**Comment by ninpnin** [comment]
The code defaults to Jan 1st if there no dates are matched.

**Comment by MansMeg** [comment]
Alright. We should probably rather marknit as missing value then. Otherwise it will be confusing when using the data. Is that consistant with the xml schema?

**Comment by ninpnin** [comment]
Apparently, the year is enough: https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-docDate.html

```xml
<docImprint>Oxford, Clarendon Press, <docDate>1987</docDate></docImprint>
```

**Comment by ninpnin** [comment]
README fixed.
