### ISSUE TITLE
Reorganize the folder structure for end user clarity

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus-old#79]
It is now not clear, as a user, what files are part of "the API" of the corpus. As I user I do not know what folders are relevant for me.

I think we want to change the folder structure so it is more intuitive:

/corpus/protocols/[YYYY]/ : The ParlaClarin XML protocols
/rpackage/ : The R functionality (as an R package) used to access and use the corpus
/pythonlib/ : The Python functionality (as a Python library) used to access and use the corpus
/curation/data/: All data we use to curate and process the data
/curation/code/: All data we use to curate and process the data
/docs/: All documentation
/test/: testing of corpus quality
/schemas/: schemas for testing formats

Some immidate changes would be:
segment-classifier -> curation/code/ ?
riksdagen_corpus -> curation/code/ ?
img -> docs/img ?
Then there would be some moving around in the data and db folders as well.

What do you think @ninpnin ?

**Comment by ninpnin** [comment]
Personally, I think one should mostly avoid nested folder structures. Oftentimes, they just end up being more confusing.

That being said, some of the folders could be reorganized. The distinction between data and db is redundant now, segment-classifier is actually a data folder containing the classifier model. I'll make some changes and keep you updated in this thread.

**Comment by ninpnin** [comment]
<img width="928" alt="Näyttökuva 2021-3-8 kello 9 50 41" src="https://user-images.githubusercontent.com/10169469/110297462-cbecb400-7ff3-11eb-86e6-56f57a58cdca.png">

Here's the current file structure in dev for reference.

**Comment by MansMeg** [comment]
So what is your alternative to my suggestion on the folder structure above? The main focus should be on the users. Now it is quite confusing where to find the corpus and the data.

I think we want to fix this asap so we can let others into the corpus (such as Miriam).

**Comment by ninpnin** [comment]
If we just say all relevant data is in ```corpus``` , the python package is in ```riksdagen_data``` and the R package is in ```rpackage``` .

Additionally, there will be a corpus zip download  under the releases section.

**Comment by MansMeg** [comment]
Sounds good. Althouth, it is not very intuitive that the python library is in riksdagen_data?

So what would be your full folder structure suggestion?

**Comment by ninpnin** [comment]
Merge db and data, and  move segment classifier in it

**Comment by ninpnin** [comment]
![Screenshot from 2021-03-09 17-59-14](https://user-images.githubusercontent.com/10169469/110508389-3fc8b280-8101-11eb-8687-79bdcda5b088.png)

I'd say the structure is pretty self-explanatory now.

**Comment by MansMeg** [comment]
Great!

**Comment by MansMeg** [comment]
Please close this issue when you merge.
