### ISSUE TITLE
Page beginnings are a bit off

### ISSUE THREAD

**Issue by ninpnin** [welfare-state-analytics/riksdagen-corpus-old#85]
Some of the page beginning blocks (```<pb>```) seem to come clustered after long utterance blocks. So the page beginnings don't quite match the data.

I would rerun the OCR -> Parla clarin pipeline to fix this. It's not feasible to do this and retain other curations, so all changes as large as this need to be dealt with quickly.

**Comment by MansMeg** [comment]
Ok. I think it is important that we see this as a curation as well (i.e. fix incorrect page beginnings). I.e. we to do this in a way that preserves done curations (even though they are small). We could see this as an example of a large automated curation of incorrect page beginnings?

**Comment by MansMeg** [comment]
Also, I guess we want to define these notes as well? That they come after a segment or utterance? Can they exist within an utterance?

**Comment by ninpnin** [comment]
We've kinda lost the original information at this point. You could try to pick up the page numbers from the text but that would be prone to errors.

**Comment by MansMeg** [comment]
I was more thinking that if you rerun the Parla-Clarin to OCR but only add the new page number notes to the documents?

I think we will run into a similar problem multiple times along the way. Then we will not be able to solve it by recreating the corpus. Hence, I think we should rather see this as a test case for what we would do if this would have happened 2 years down the line. 

How would you have solved the problem then?

**Comment by ninpnin** [comment]
With all kinds of stitching and patching...

All content is already included, the order's just incorrect. But since Parla-Clarin has a somewhat semantic stucture, you can't just reorder the blocks. Furthermore, you'd need to match the blocks from the original source and Parla-Clarin if you wanted to refetch the order.

**Comment by MansMeg** [comment]
Ok. Can we do it smarter somehow? Can we identify which notes are incorrect?

**Comment by ninpnin** [comment]
I think we don't want to build a separate apparatus for that. On top of that, we had a plan of getting rid of the extra git history at some point before the actual release. The repo is approaching 20GB even though the actual data is just 4GB or so.

I suggest:

- I'll rerun the pipeline
- I'll manually check roughly 20 pages and see that no content blocks are missing, and that everything is in corrent order
- We call that the starting point of the corpus
- I'll erase git history, and maybe keep it locally if we really need it after that point

**Comment by ninpnin** [comment]
After all, the requirements are not too high.

- All paragraphs are included on the page
- No extra paragraphs are on the page
- The paragraphs are in correct order

So far, we haven't really checked this in the corpus.

**Comment by MansMeg** [comment]
Alright! Fair enough. Then 0.2 is the starting point essentially. That seems like a good solution.

Then, if I understand you correctly, from this point on, we only curate the original corpus?

Can you extract the manual curations we have done so far using the notes? And then add them afterwards?

**Comment by ninpnin** [comment]
There are only a few, but yes they can be extracted from the current corpus.

**Comment by MansMeg** [comment]
Great! 

Then I understand this as we reboot the corpus for version 0.2 but add the current manual annotations that have been done?
